version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pincex
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build: .
    depends_on:
      - db
      - redis
    environment:
      PORT: 8080
      DB_URL: postgres://user:pass@db:5432/pincex?sslmode=disable
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8080:8080"
