// moved from internal/userauth/grpc/userauth.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: userauth.proto

package userauth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Token validation
type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_userauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_userauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ValidateTokenResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ValidateTokenResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ValidateTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ValidateTokenResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Token refresh
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_userauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_userauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RefreshTokenResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// API Key creation
type CreateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_userauth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAPIKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CreateAPIKeyRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyResponse) Reset() {
	*x = CreateAPIKeyResponse{}
	mi := &file_userauth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyResponse) ProtoMessage() {}

func (x *CreateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAPIKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateAPIKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateAPIKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *CreateAPIKeyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// API Key validation
type ValidateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyRequest) Reset() {
	*x = ValidateAPIKeyRequest{}
	mi := &file_userauth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyRequest) ProtoMessage() {}

func (x *ValidateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ValidateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyResponse) Reset() {
	*x = ValidateAPIKeyResponse{}
	mi := &file_userauth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyResponse) ProtoMessage() {}

func (x *ValidateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateAPIKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAPIKeyResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ValidateAPIKeyResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ValidateAPIKeyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// User lookup
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_userauth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_userauth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	EmailVerified bool                   `protobuf:"varint,5,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_userauth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{10}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// User permissions
type GetUserPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsRequest) Reset() {
	*x = GetUserPermissionsRequest{}
	mi := &file_userauth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRequest) ProtoMessage() {}

func (x *GetUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsResponse) Reset() {
	*x = GetUserPermissionsResponse{}
	mi := &file_userauth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponse) ProtoMessage() {}

func (x *GetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserPermissionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserPermissionsResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetUserPermissionsResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetUserPermissionsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Role checking
type CheckUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserRoleRequest) Reset() {
	*x = CheckUserRoleRequest{}
	mi := &file_userauth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserRoleRequest) ProtoMessage() {}

func (x *CheckUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserRoleRequest.ProtoReflect.Descriptor instead.
func (*CheckUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{13}
}

func (x *CheckUserRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckUserRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CheckUserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasRole       bool                   `protobuf:"varint,1,opt,name=has_role,json=hasRole,proto3" json:"has_role,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserRoleResponse) Reset() {
	*x = CheckUserRoleResponse{}
	mi := &file_userauth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserRoleResponse) ProtoMessage() {}

func (x *CheckUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserRoleResponse.ProtoReflect.Descriptor instead.
func (*CheckUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{14}
}

func (x *CheckUserRoleResponse) GetHasRole() bool {
	if x != nil {
		return x.HasRole
	}
	return false
}

func (x *CheckUserRoleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Rate limiting
type CheckRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateLimitRequest) Reset() {
	*x = CheckRateLimitRequest{}
	mi := &file_userauth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateLimitRequest) ProtoMessage() {}

func (x *CheckRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateLimitRequest.ProtoReflect.Descriptor instead.
func (*CheckRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{15}
}

func (x *CheckRateLimitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckRateLimitRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *CheckRateLimitRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type CheckRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Remaining     int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	ResetTime     int32                  `protobuf:"varint,3,opt,name=reset_time,json=resetTime,proto3" json:"reset_time,omitempty"`
	Tier          string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateLimitResponse) Reset() {
	*x = CheckRateLimitResponse{}
	mi := &file_userauth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateLimitResponse) ProtoMessage() {}

func (x *CheckRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateLimitResponse.ProtoReflect.Descriptor instead.
func (*CheckRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{16}
}

func (x *CheckRateLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckRateLimitResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckRateLimitResponse) GetResetTime() int32 {
	if x != nil {
		return x.ResetTime
	}
	return 0
}

func (x *CheckRateLimitResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *CheckRateLimitResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetRateLimitStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateLimitStatusRequest) Reset() {
	*x = GetRateLimitStatusRequest{}
	mi := &file_userauth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateLimitStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateLimitStatusRequest) ProtoMessage() {}

func (x *GetRateLimitStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateLimitStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRateLimitStatusRequest) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{17}
}

func (x *GetRateLimitStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRateLimitStatusResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Success       bool                      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Limits        map[string]*RateLimitInfo `protobuf:"bytes,2,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ErrorMessage  string                    `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateLimitStatusResponse) Reset() {
	*x = GetRateLimitStatusResponse{}
	mi := &file_userauth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateLimitStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateLimitStatusResponse) ProtoMessage() {}

func (x *GetRateLimitStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateLimitStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRateLimitStatusResponse) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{18}
}

func (x *GetRateLimitStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRateLimitStatusResponse) GetLimits() map[string]*RateLimitInfo {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *GetRateLimitStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RateLimitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remaining     int32                  `protobuf:"varint,1,opt,name=remaining,proto3" json:"remaining,omitempty"`
	ResetTime     int32                  `protobuf:"varint,2,opt,name=reset_time,json=resetTime,proto3" json:"reset_time,omitempty"`
	Tier          string                 `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitInfo) Reset() {
	*x = RateLimitInfo{}
	mi := &file_userauth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitInfo) ProtoMessage() {}

func (x *RateLimitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitInfo.ProtoReflect.Descriptor instead.
func (*RateLimitInfo) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{19}
}

func (x *RateLimitInfo) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *RateLimitInfo) GetResetTime() int32 {
	if x != nil {
		return x.ResetTime
	}
	return 0
}

func (x *RateLimitInfo) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

// Health check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_userauth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{20}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_userauth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userauth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_userauth_proto_rawDescGZIP(), []int{21}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_userauth_proto protoreflect.FileDescriptor

const file_userauth_proto_rawDesc = "" +
	"\n" +
	"\x0euserauth.proto\x12\buserauth\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xf4\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xd8\x01\n" +
	"\x14RefreshTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\x9f\x01\n" +
	"\x13CreateAPIKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x85\x01\n" +
	"\x14CreateAPIKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"0\n" +
	"\x15ValidateAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"\xe0\x01\n" +
	"\x16ValidateAPIKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"p\n" +
	"\x0fGetUserResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\"\n" +
	"\x04user\x18\x02 \x01(\v2\x0e.userauth.UserR\x04user\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x82\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12%\n" +
	"\x0eemail_verified\x18\x05 \x01(\bR\remailVerified\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"4\n" +
	"\x19GetUserPermissionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x93\x01\n" +
	"\x1aGetUserPermissionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"C\n" +
	"\x14CheckUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"W\n" +
	"\x15CheckUserRoleResponse\x12\x19\n" +
	"\bhas_role\x18\x01 \x01(\bR\ahasRole\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"i\n" +
	"\x15CheckRateLimitRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\"\xa8\x01\n" +
	"\x16CheckRateLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\x12\x1d\n" +
	"\n" +
	"reset_time\x18\x03 \x01(\x05R\tresetTime\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"4\n" +
	"\x19GetRateLimitStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xf9\x01\n" +
	"\x1aGetRateLimitStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12H\n" +
	"\x06limits\x18\x02 \x03(\v20.userauth.GetRateLimitStatusResponse.LimitsEntryR\x06limits\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x1aR\n" +
	"\vLimitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.userauth.RateLimitInfoR\x05value:\x028\x01\"`\n" +
	"\rRateLimitInfo\x12\x1c\n" +
	"\tremaining\x18\x01 \x01(\x05R\tremaining\x12\x1d\n" +
	"\n" +
	"reset_time\x18\x02 \x01(\x05R\tresetTime\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\tR\x04tier\"\x14\n" +
	"\x12HealthCheckRequest\"\x83\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xcb\x06\n" +
	"\x0fUserAuthService\x12P\n" +
	"\rValidateToken\x12\x1e.userauth.ValidateTokenRequest\x1a\x1f.userauth.ValidateTokenResponse\x12M\n" +
	"\fRefreshToken\x12\x1d.userauth.RefreshTokenRequest\x1a\x1e.userauth.RefreshTokenResponse\x12M\n" +
	"\fCreateAPIKey\x12\x1d.userauth.CreateAPIKeyRequest\x1a\x1e.userauth.CreateAPIKeyResponse\x12S\n" +
	"\x0eValidateAPIKey\x12\x1f.userauth.ValidateAPIKeyRequest\x1a .userauth.ValidateAPIKeyResponse\x12>\n" +
	"\aGetUser\x12\x18.userauth.GetUserRequest\x1a\x19.userauth.GetUserResponse\x12_\n" +
	"\x12GetUserPermissions\x12#.userauth.GetUserPermissionsRequest\x1a$.userauth.GetUserPermissionsResponse\x12P\n" +
	"\rCheckUserRole\x12\x1e.userauth.CheckUserRoleRequest\x1a\x1f.userauth.CheckUserRoleResponse\x12S\n" +
	"\x0eCheckRateLimit\x12\x1f.userauth.CheckRateLimitRequest\x1a .userauth.CheckRateLimitResponse\x12_\n" +
	"\x12GetRateLimitStatus\x12#.userauth.GetRateLimitStatusRequest\x1a$.userauth.GetRateLimitStatusResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.userauth.HealthCheckRequest\x1a\x1d.userauth.HealthCheckResponseB8Z6github.com/Aidin1998/pincex_unified/pkg/proto/userauthb\x06proto3"

var (
	file_userauth_proto_rawDescOnce sync.Once
	file_userauth_proto_rawDescData []byte
)

func file_userauth_proto_rawDescGZIP() []byte {
	file_userauth_proto_rawDescOnce.Do(func() {
		file_userauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userauth_proto_rawDesc), len(file_userauth_proto_rawDesc)))
	})
	return file_userauth_proto_rawDescData
}

var file_userauth_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_userauth_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),       // 0: userauth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),      // 1: userauth.ValidateTokenResponse
	(*RefreshTokenRequest)(nil),        // 2: userauth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),       // 3: userauth.RefreshTokenResponse
	(*CreateAPIKeyRequest)(nil),        // 4: userauth.CreateAPIKeyRequest
	(*CreateAPIKeyResponse)(nil),       // 5: userauth.CreateAPIKeyResponse
	(*ValidateAPIKeyRequest)(nil),      // 6: userauth.ValidateAPIKeyRequest
	(*ValidateAPIKeyResponse)(nil),     // 7: userauth.ValidateAPIKeyResponse
	(*GetUserRequest)(nil),             // 8: userauth.GetUserRequest
	(*GetUserResponse)(nil),            // 9: userauth.GetUserResponse
	(*User)(nil),                       // 10: userauth.User
	(*GetUserPermissionsRequest)(nil),  // 11: userauth.GetUserPermissionsRequest
	(*GetUserPermissionsResponse)(nil), // 12: userauth.GetUserPermissionsResponse
	(*CheckUserRoleRequest)(nil),       // 13: userauth.CheckUserRoleRequest
	(*CheckUserRoleResponse)(nil),      // 14: userauth.CheckUserRoleResponse
	(*CheckRateLimitRequest)(nil),      // 15: userauth.CheckRateLimitRequest
	(*CheckRateLimitResponse)(nil),     // 16: userauth.CheckRateLimitResponse
	(*GetRateLimitStatusRequest)(nil),  // 17: userauth.GetRateLimitStatusRequest
	(*GetRateLimitStatusResponse)(nil), // 18: userauth.GetRateLimitStatusResponse
	(*RateLimitInfo)(nil),              // 19: userauth.RateLimitInfo
	(*HealthCheckRequest)(nil),         // 20: userauth.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 21: userauth.HealthCheckResponse
	nil,                                // 22: userauth.GetRateLimitStatusResponse.LimitsEntry
	(*timestamppb.Timestamp)(nil),      // 23: google.protobuf.Timestamp
}
var file_userauth_proto_depIdxs = []int32{
	23, // 0: userauth.ValidateTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	23, // 1: userauth.RefreshTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	23, // 2: userauth.CreateAPIKeyRequest.expires_at:type_name -> google.protobuf.Timestamp
	23, // 3: userauth.ValidateAPIKeyResponse.expires_at:type_name -> google.protobuf.Timestamp
	10, // 4: userauth.GetUserResponse.user:type_name -> userauth.User
	23, // 5: userauth.User.created_at:type_name -> google.protobuf.Timestamp
	23, // 6: userauth.User.updated_at:type_name -> google.protobuf.Timestamp
	22, // 7: userauth.GetRateLimitStatusResponse.limits:type_name -> userauth.GetRateLimitStatusResponse.LimitsEntry
	23, // 8: userauth.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	19, // 9: userauth.GetRateLimitStatusResponse.LimitsEntry.value:type_name -> userauth.RateLimitInfo
	0,  // 10: userauth.UserAuthService.ValidateToken:input_type -> userauth.ValidateTokenRequest
	2,  // 11: userauth.UserAuthService.RefreshToken:input_type -> userauth.RefreshTokenRequest
	4,  // 12: userauth.UserAuthService.CreateAPIKey:input_type -> userauth.CreateAPIKeyRequest
	6,  // 13: userauth.UserAuthService.ValidateAPIKey:input_type -> userauth.ValidateAPIKeyRequest
	8,  // 14: userauth.UserAuthService.GetUser:input_type -> userauth.GetUserRequest
	11, // 15: userauth.UserAuthService.GetUserPermissions:input_type -> userauth.GetUserPermissionsRequest
	13, // 16: userauth.UserAuthService.CheckUserRole:input_type -> userauth.CheckUserRoleRequest
	15, // 17: userauth.UserAuthService.CheckRateLimit:input_type -> userauth.CheckRateLimitRequest
	17, // 18: userauth.UserAuthService.GetRateLimitStatus:input_type -> userauth.GetRateLimitStatusRequest
	20, // 19: userauth.UserAuthService.HealthCheck:input_type -> userauth.HealthCheckRequest
	1,  // 20: userauth.UserAuthService.ValidateToken:output_type -> userauth.ValidateTokenResponse
	3,  // 21: userauth.UserAuthService.RefreshToken:output_type -> userauth.RefreshTokenResponse
	5,  // 22: userauth.UserAuthService.CreateAPIKey:output_type -> userauth.CreateAPIKeyResponse
	7,  // 23: userauth.UserAuthService.ValidateAPIKey:output_type -> userauth.ValidateAPIKeyResponse
	9,  // 24: userauth.UserAuthService.GetUser:output_type -> userauth.GetUserResponse
	12, // 25: userauth.UserAuthService.GetUserPermissions:output_type -> userauth.GetUserPermissionsResponse
	14, // 26: userauth.UserAuthService.CheckUserRole:output_type -> userauth.CheckUserRoleResponse
	16, // 27: userauth.UserAuthService.CheckRateLimit:output_type -> userauth.CheckRateLimitResponse
	18, // 28: userauth.UserAuthService.GetRateLimitStatus:output_type -> userauth.GetRateLimitStatusResponse
	21, // 29: userauth.UserAuthService.HealthCheck:output_type -> userauth.HealthCheckResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_userauth_proto_init() }
func file_userauth_proto_init() {
	if File_userauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userauth_proto_rawDesc), len(file_userauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userauth_proto_goTypes,
		DependencyIndexes: file_userauth_proto_depIdxs,
		MessageInfos:      file_userauth_proto_msgTypes,
	}.Build()
	File_userauth_proto = out.File
	file_userauth_proto_goTypes = nil
	file_userauth_proto_depIdxs = nil
}
