// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: marketdata.proto

package marketdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to subscribe to market data
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Levels        []int32                `protobuf:"varint,3,rep,packed,name=levels,proto3" json:"levels,omitempty"`
	Frequency     *durationpb.Duration   `protobuf:"bytes,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Compression   string                 `protobuf:"bytes,5,opt,name=compression,proto3" json:"compression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_marketdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SubscribeRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubscribeRequest) GetLevels() []int32 {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *SubscribeRequest) GetFrequency() *durationpb.Duration {
	if x != nil {
		return x.Frequency
	}
	return nil
}

func (x *SubscribeRequest) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

// Market data update message
type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PriceLevel    int32                  `protobuf:"varint,2,opt,name=price_level,json=priceLevel,proto3" json:"price_level,omitempty"`
	Bid           float64                `protobuf:"fixed64,3,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask           float64                `protobuf:"fixed64,4,opt,name=ask,proto3" json:"ask,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_marketdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{1}
}

func (x *Update) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Update) GetPriceLevel() int32 {
	if x != nil {
		return x.PriceLevel
	}
	return 0
}

func (x *Update) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *Update) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *Update) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_marketdata_proto protoreflect.FileDescriptor

const file_marketdata_proto_rawDesc = "" +
	"\n" +
	"\x10marketdata.proto\x12\n" +
	"marketdata\x1a\x1egoogle/protobuf/duration.proto\"\xba\x01\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06levels\x18\x03 \x03(\x05R\x06levels\x127\n" +
	"\tfrequency\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\tfrequency\x12 \n" +
	"\vcompression\x18\x05 \x01(\tR\vcompression\"\x83\x01\n" +
	"\x06Update\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1f\n" +
	"\vprice_level\x18\x02 \x01(\x05R\n" +
	"priceLevel\x12\x10\n" +
	"\x03bid\x18\x03 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\x04 \x01(\x01R\x03ask\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp2O\n" +
	"\n" +
	"MarketData\x12A\n" +
	"\tSubscribe\x12\x1c.marketdata.SubscribeRequest\x1a\x12.marketdata.Update\"\x000\x01B>Z<github.com/Aidin1998/finalex/pkg/proto/marketdata;marketdatab\x06proto3"

var (
	file_marketdata_proto_rawDescOnce sync.Once
	file_marketdata_proto_rawDescData []byte
)

func file_marketdata_proto_rawDescGZIP() []byte {
	file_marketdata_proto_rawDescOnce.Do(func() {
		file_marketdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketdata_proto_rawDesc), len(file_marketdata_proto_rawDesc)))
	})
	return file_marketdata_proto_rawDescData
}

var file_marketdata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_marketdata_proto_goTypes = []any{
	(*SubscribeRequest)(nil),    // 0: marketdata.SubscribeRequest
	(*Update)(nil),              // 1: marketdata.Update
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_marketdata_proto_depIdxs = []int32{
	2, // 0: marketdata.SubscribeRequest.frequency:type_name -> google.protobuf.Duration
	0, // 1: marketdata.MarketData.Subscribe:input_type -> marketdata.SubscribeRequest
	1, // 2: marketdata.MarketData.Subscribe:output_type -> marketdata.Update
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_marketdata_proto_init() }
func file_marketdata_proto_init() {
	if File_marketdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketdata_proto_rawDesc), len(file_marketdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketdata_proto_goTypes,
		DependencyIndexes: file_marketdata_proto_depIdxs,
		MessageInfos:      file_marketdata_proto_msgTypes,
	}.Build()
	File_marketdata_proto = out.File
	file_marketdata_proto_goTypes = nil
	file_marketdata_proto_depIdxs = nil
}
