# Example Kubernetes deployment for the market data WebSocket service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketdata-ws
spec:
  replicas: 3
  selector:
    matchLabels:
      app: marketdata-ws
  template:
    metadata:
      labels:
        app: marketdata-ws
    spec:
      containers:
      - name: marketdata-ws
        image: pincex/marketdata-ws:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: marketdata-ws
spec:
  selector:
    app: marketdata-ws
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketdata-ws
spec:
  rules:
  - http:
      paths:
      - path: /ws/marketdata
        pathType: Prefix
        backend:
          service:
            name: marketdata-ws
            port:
              number: 80
