// Package docs Code generated by swag; DO NOT EDIT.
// This file was generated by swaggo/swag
package docs

import swaggerFiles "github.com/swaggo/files"
import ginSwagger "github.com/swaggo/gin-swagger"

const DocTemplate = ""

var SwaggerInfo = struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}{}

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfoInstance = swaggerInfo{
	Version:     "1.0.0",
	Host:        "localhost:8080",
	BasePath:    "/api/v1",
	Schemes:     []string{"http", "https"},
	Title:       "PinCEX Unified API",
	Description: "Comprehensive Swagger documentation for the PinCEX Unified Exchange API.",
}

func init() {
	SwaggerInfo.Version = SwaggerInfoInstance.Version
	SwaggerInfo.Host = SwaggerInfoInstance.Host
	SwaggerInfo.BasePath = SwaggerInfoInstance.BasePath
	SwaggerInfo.Schemes = SwaggerInfoInstance.Schemes
	SwaggerInfo.Title = SwaggerInfoInstance.Title
	SwaggerInfo.Description = SwaggerInfoInstance.Description
}

// WrapHandler wraps swaggerFiles.Handler
func WrapHandler(handler func(http.ResponseWriter, *http.Request)) gin.HandlerFunc {
	return ginSwagger.WrapHandler(swaggerFiles.Handler)
}
