apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiat-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fiat-gateway
  template:
    metadata:
      labels:
        app: fiat-gateway
    spec:
      containers:
      - name: fiat-gateway
        image: yourrepo/fiat-gateway:latest
        envFrom:
        - secretRef:
            name: fiat-gateway-secrets
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
