name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
      - name: Run linter
        run: golangci-lint run ./...

  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: pincex
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U user && break
            sleep 2
          done
      - name: Set DB DSN
        run: echo "PINCEX_DATABASE_DSN=postgresql://user:pass@localhost:5432/pincex?sslmode=disable" >> $GITHUB_ENV
      - name: Run migrations
        run: bash scripts/migrate.sh
      - name: Partition maintenance
        run: bash scripts/partition_maintenance.sh
      - name: Run tests
        run: go test ./... -v

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: go build -o pincex ./cmd/pincex
      - name: Build Docker image
        run: |
          docker build -t pincex:latest .
