name: Performance Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: make build
      - name: Start services (docker-compose)
        run: docker-compose up -d
      - name: Run performance tests
        run: |
          go test -v -run=^$ ./internal/trading/ ./internal/wallet/ ./internal/bookkeeper/ -bench=. -benchmem | tee perf.log
      - name: Upload perf log
        uses: actions/upload-artifact@v4
        with:
          name: perf-log
          path: perf.log
